/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JDlgFornecedorNovo;

import bean.FornecedorBbd;
import dao.FornecedorDao_bbd;
import java.util.List;
import tools.Util;

/**
 *
 * @author "Autor"
 */
public class JDlgFornecedorNovo extends javax.swing.JDialog {

    /**
     * Creates new form JDlgFornecedorIA2
     */
    FornecedorControle fornecedorControle;
    FornecedorDao_bbd fornecedorDao_bbd;
    JDlgFornecedorIA jDlgFornecedor;
    FornecedorBbd fornecedorBbd;
    List lista;

    public JDlgFornecedorNovo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        fornecedorControle = new FornecedorControle();
        fornecedorDao_bbd = new FornecedorDao_bbd();

        fornecedorBbd = new FornecedorBbd();

        lista = fornecedorDao_bbd.listAll();
        fornecedorControle.setList(lista);
        jTable1.setModel(fornecedorControle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnIncluir_bbd = new javax.swing.JButton();
        jBtnExcluir_bbd = new javax.swing.JButton();
        jBtnAlterar_bbd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnIncluir_bbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jBtnIncluir_bbd.setText("Incluir");
        jBtnIncluir_bbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_bbdActionPerformed(evt);
            }
        });

        jBtnExcluir_bbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir_bbd.setText("Excluir");
        jBtnExcluir_bbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_bbdActionPerformed(evt);
            }
        });

        jBtnAlterar_bbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar_bbd.setText("Alterar");
        jBtnAlterar_bbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_bbdActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnIncluir_bbd)
                .addGap(18, 18, 18)
                .addComponent(jBtnAlterar_bbd)
                .addGap(18, 18, 18)
                .addComponent(jBtnExcluir_bbd)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAlterar_bbd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnExcluir_bbd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnIncluir_bbd)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluir_bbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_bbdActionPerformed
        // TODO add your handling code here:
        jDlgFornecedor = new JDlgFornecedorIA(null, true);
        jDlgFornecedor.setTelaAnterio(this);
        jDlgFornecedor.setTitle("Incluindo");
        jDlgFornecedor.setVisible(true);
    }//GEN-LAST:event_jBtnIncluir_bbdActionPerformed

    private void jBtnExcluir_bbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_bbdActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Deseja excluir?")) {
            if (jTable1.getSelectedRow() == -1) {
                Util.mensagem("Selecione uma linha antes");
            } else {
                fornecedorDao_bbd.delete(fornecedorControle.getBean(jTable1.getSelectedRow()));
                fornecedorControle.removeList(jTable1.getSelectedRow());
                Util.mensagem("Excluido");
            }
        } else {
            Util.mensagem("Exclusão cancelada");
        }
    }//GEN-LAST:event_jBtnExcluir_bbdActionPerformed

    private void jBtnAlterar_bbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_bbdActionPerformed
        // TODO add your handling code here:

          if (jTable1.getSelectedRow() == -1) {
            Util.mensagem("Selecione uma linha Para alterar!");
        } else {
            JDlgFornecedorIA jDlgFornecedor = new JDlgFornecedorIA(null, true);
            jDlgFornecedor.setTelaAnterio(this);
            jDlgFornecedor.setTitle("Alterar");
            jDlgFornecedor.ativar();
            jDlgFornecedor.beanView(fornecedorControle.getBean(jTable1.getSelectedRow()));
            jDlgFornecedor.setVisible(true);
        }
    }//GEN-LAST:event_jBtnAlterar_bbdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedorNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedorNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedorNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedorNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFornecedorNovo dialog = new JDlgFornecedorNovo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar_bbd;
    private javax.swing.JButton jBtnExcluir_bbd;
    private javax.swing.JButton jBtnIncluir_bbd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
