/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.GrupoBbd;
import dao.GrupoDao_bbd;
import java.util.ArrayList;
import tools.Util;

/**
 *
 * @author Usuario
 */
public class JDlgGrupo extends javax.swing.JDialog {

        public GrupoDao_bbd grupoDao_bbd;
        public GrupoBbd grupoBbd;
        Boolean incluindo;
        
    public JDlgGrupo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Grupo");
        setLocationRelativeTo(null);
        habilitar(false);
        grupoDao_bbd = new GrupoDao_bbd();
        grupoBbd = new GrupoBbd();
    }
    public void habilitar(boolean valor) {
        Util.habilitar(valor, JtxtCodigo_bbd, JtxtNome_bbd, JtxtTipo_bbd, jTxtCategoriaBbd,jCboAtivoBbd, jBtnConfirmar_bbd, jBtnCancelar_bbd);
        Util.habilitar(valor, jBtnIncluir_bbd, jBtnAlterar_bbd, jBtnExcluir_bbd);
        Util.habilitar(!valor, jBtnIncluir_bbd, jBtnAlterar_bbd, jBtnExcluir_bbd, jBtnPesquisar_bbd);
    }
    
       public GrupoBbd viewBean() {
        GrupoBbd grupoBbd = new GrupoBbd();
        grupoBbd.setIdGrupoBbd(Integer.parseInt(JtxtCodigo_bbd.getText()));
        grupoBbd.setNomeBbd(JtxtNome_bbd.getText());
        grupoBbd.setTipoBbd(JtxtTipo_bbd.getText());
        grupoBbd.setCategoriaBbd(jTxtCategoriaBbd.getText());
        grupoBbd.setAtivoBbd(jCboAtivoBbd.isSelected() == true ? 1 : 2);

        return grupoBbd;
    }

    public void beanView(GrupoBbd grupoBdb) {
        JtxtCodigo_bbd.setText(String.valueOf(grupoBdb.getIdGrupoBbd()));
        JtxtNome_bbd.setText(grupoBdb.getNomeBbd());
        JtxtTipo_bbd.setText(grupoBdb.getTipoBbd());
        jTxtCategoriaBbd.setText(String.valueOf(grupoBdb.getCategoriaBbd()));
        
          if (grupoBbd.getAtivoBbd().equals(1) == true) { 
           jCboAtivoBbd.setSelected(true);
       }else {
           jCboAtivoBbd.setSelected(false);
       }

    }
    /*
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JtxtCodigo_bbd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JtxtNome_bbd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JtxtTipo_bbd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtCategoriaBbd = new javax.swing.JTextField();
        jCboAtivoBbd = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jBtnPesquisar_bbd = new javax.swing.JButton();
        jBtnIncluir_bbd = new javax.swing.JButton();
        jBtnAlterar_bbd = new javax.swing.JButton();
        jBtnExcluir_bbd = new javax.swing.JButton();
        jBtnConfirmar_bbd = new javax.swing.JButton();
        jBtnCancelar_bbd = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("código");

        jLabel3.setText("Nome");

        jLabel4.setText("Tipo");

        jLabel6.setText("Categoria");

        jCboAtivoBbd.setText("ativo");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtnPesquisar_bbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar_bbd.setText("Pesquisar");
        jBtnPesquisar_bbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisar_bbdActionPerformed(evt);
            }
        });

        jBtnIncluir_bbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir_1.png"))); // NOI18N
        jBtnIncluir_bbd.setText("Incluir");
        jBtnIncluir_bbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_bbdActionPerformed(evt);
            }
        });

        jBtnAlterar_bbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar_bbd.setText("Alterar");
        jBtnAlterar_bbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_bbdActionPerformed(evt);
            }
        });

        jBtnExcluir_bbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir_bbd.setText("Excluir");
        jBtnExcluir_bbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_bbdActionPerformed(evt);
            }
        });

        jBtnConfirmar_bbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnConfirmar_bbd.setText("Confirmar");
        jBtnConfirmar_bbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_bbdActionPerformed(evt);
            }
        });

        jBtnCancelar_bbd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar_bbd.setText("Cancelar");
        jBtnCancelar_bbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_bbdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnIncluir_bbd)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jBtnAlterar_bbd)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jBtnExcluir_bbd)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jBtnConfirmar_bbd)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jBtnCancelar_bbd)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jBtnPesquisar_bbd)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnIncluir_bbd)
                        .addComponent(jBtnAlterar_bbd)
                        .addComponent(jBtnExcluir_bbd)
                        .addComponent(jBtnConfirmar_bbd)
                        .addComponent(jBtnCancelar_bbd)
                        .addComponent(jBtnPesquisar_bbd))
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(JtxtCodigo_bbd)
                    .addComponent(JtxtNome_bbd)
                    .addComponent(JtxtTipo_bbd, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTxtCategoriaBbd, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jCboAtivoBbd)))
                .addContainerGap(219, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JtxtCodigo_bbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCategoriaBbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCboAtivoBbd)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JtxtNome_bbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JtxtTipo_bbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPesquisar_bbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisar_bbdActionPerformed
        // TODO add your handling code here:
          grupoBbd = new GrupoBbd();
          JDlgGrupoPesquisar jDlgGrupoPesquisar  = new JDlgGrupoPesquisar (null, true);
          jDlgGrupoPesquisar.setTelaAnterior(this);
          jDlgGrupoPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisar_bbdActionPerformed

    private void jBtnIncluir_bbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_bbdActionPerformed
        // TODO add your handling code here:
        grupoBbd = new GrupoBbd();
        habilitar(true);
        limparCampos();
        incluindo = true;
    }//GEN-LAST:event_jBtnIncluir_bbdActionPerformed

    private void jBtnAlterar_bbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_bbdActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        JtxtCodigo_bbd.setEnabled(false);
        incluindo = false;
    }//GEN-LAST:event_jBtnAlterar_bbdActionPerformed

    private void jBtnExcluir_bbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_bbdActionPerformed
        // TODO add your handling code here:
         if (grupoBbd!= null) {
            if(Util.perguntar("Deseja excluir?")){
                grupoBbd = viewBean();
                grupoDao_bbd = new GrupoDao_bbd();
                limparCampos();
                grupoBbd = null;
                Util.mensagem("Excluido");
                limparCampos();
            } else {
                Util.mensagem("exclusão cancelada");
            }   
        } else{
            Util.mensagem("Nenhuma linha selecioanda");
        }
         
    }//GEN-LAST:event_jBtnExcluir_bbdActionPerformed

    private void jBtnConfirmar_bbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_bbdActionPerformed
        // TODO add your handling code here:
          grupoBbd = viewBean();
          grupoDao_bbd = new GrupoDao_bbd();
        if (incluindo == true) {
            grupoDao_bbd.insert(grupoBbd);
        } else {
            grupoDao_bbd.update(grupoBbd);
        }
        habilitar(false);
        limparCampos();

    }//GEN-LAST:event_jBtnConfirmar_bbdActionPerformed

    private void jBtnCancelar_bbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_bbdActionPerformed
        // TODO add your handling code here:
        habilitar(false);
        Util.limparCampos(JtxtCodigo_bbd, JtxtNome_bbd, JtxtTipo_bbd, jTxtCategoriaBbd,jCboAtivoBbd );
        Util.mensagem("Cancelado");
    }//GEN-LAST:event_jBtnCancelar_bbdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgGrupo dialog = new JDlgGrupo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxtCodigo_bbd;
    private javax.swing.JTextField JtxtNome_bbd;
    private javax.swing.JTextField JtxtTipo_bbd;
    private javax.swing.JButton jBtnAlterar_bbd;
    private javax.swing.JButton jBtnCancelar_bbd;
    private javax.swing.JButton jBtnConfirmar_bbd;
    private javax.swing.JButton jBtnExcluir_bbd;
    private javax.swing.JButton jBtnIncluir_bbd;
    private javax.swing.JButton jBtnPesquisar_bbd;
    private javax.swing.JCheckBox jCboAtivoBbd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtCategoriaBbd;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
    }
}
