/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.FornecedorBbd;
import dao.FornecedorDao_bbd;
import dao.CompraDao_bbd;
import dao.CompraProdutoDao_Bbd;
import bean.CompraBbd;
import bean.FornecedorBbd;
import bean.CompraProdutoBbd;
import controle.CompraProdutoControle;
import controle.CompraControle;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author 04863235100
 */

public class JDlgCompra extends javax.swing.JDialog {

    MaskFormatter mascaraData;

    private boolean incluindo;
    private CompraDao_bbd compraDao_bbd;
    CompraBbd compraBbd;
    CompraControle compraControle;
    CompraProdutoControle compraProdutoControle;
    FornecedorDao_bbd fornecedorDao_bbd;
    FornecedorBbd fornecedorBbd;

    public JDlgCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("COMPRA DE MAQUIAGEM");
        compraDao_bbd = new CompraDao_bbd();
        List lista = new ArrayList();

        FornecedorDao_bbd fornecedorDao_bbd = new FornecedorDao_bbd();
        List listaFor = fornecedorDao_bbd.listAll();
        for (int i = 0; i < listaFor.size(); i++) {
            jCboFornecedor_bbd.addItem(((FornecedorBbd) listaFor.get(i)));
        }

        compraProdutoControle = new CompraProdutoControle();
        compraProdutoControle.setList(lista);
        jTable1.setModel(compraProdutoControle);

                     
    }
    
    
    public void habilitar(boolean valor) {
        Util.habilitar(valor, jTxtNumCompra, jFmtData, jCboFornecedor_bbd, jTxtTotal, jBtnConfirmar, jBtnCancelar);
        Util.habilitar(valor, jBtnIncluirbbd, jBtnAlterarbbd, jBtnExcluirbbd);
        Util.habilitar(!valor, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
    }
    
       public CompraBbd viewBean() {
        CompraBbd compraBdb = new CompraBbd();
        compraBdb.setIdcompraBbd(Integer.parseInt(jTxtNumCompra.getText()));
        compraBdb.setDataCompraBbd(Util.strDate(jFmtData.getText()));
        compraBdb.setFornecedorBbd((FornecedorBbd) jCboFornecedor_bbd.getSelectedItem());
        compraBdb.setTotalBbd(Util.strDouble(jTxtTotal.getText()));
       
        return compraBdb;
    }

    public void beanView(CompraBbd compraBdb) {
        jTxtNumCompra.setText(String.valueOf(compraBdb.getIdcompraBbd()));
        jFmtData.setText(Util.dateStr(compraBdb.getDataCompraBbd()));
        jCboFornecedor_bbd.setSelectedItem(compraBdb.getFornecedorBbd());
        jTxtTotal.setText(String.valueOf(compraBdb.getTotalBbd()));
        
        CompraProdutoDao_Bbd compraProdutoDAO = new CompraProdutoDao_Bbd();
        List listaProd = (List) compraProdutoDAO.ListProdutos(compraBdb);

        compraProdutoControle.setList(listaProd);
        jTable1.setModel(compraProdutoControle);
    }

    public int getSelectedRowProd() {
        return jTable1.getSelectedRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnAlterarbbd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBtnIncluirbbd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTxtNumCompra = new javax.swing.JTextField();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jCboFornecedor_bbd = new javax.swing.JComboBox<FornecedorBbd>();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jFmtData = new javax.swing.JTextField();
        jBtnAlterar = new javax.swing.JButton();
        jTxtTotal = new javax.swing.JTextField();
        jBtnIncluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBtnExcluirbbd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnAlterarbbd.setText("alterar");
        jBtnAlterarbbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarbbdActionPerformed(evt);
            }
        });

        jLabel3.setText("Fornecedor:");

        jBtnIncluirbbd.setText("Incluir");
        jBtnIncluirbbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirbbdActionPerformed(evt);
            }
        });

        jLabel2.setText("Data:");

        jLabel1.setText("Numero de compra:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmar.setText("confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jLabel5.setText("Total");

        jBtnExcluirbbd.setText("excluir");
        jBtnExcluirbbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirbbdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtNumCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jCboFornecedor_bbd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBtnExcluirbbd)
                                .addComponent(jBtnAlterarbbd))
                            .addComponent(jBtnIncluirbbd))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNumCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboFornecedor_bbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jBtnIncluirbbd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterarbbd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluirbbd)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnIncluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
         habilitar(false);
        Util.limparCampos(jTxtNumCompra, jFmtData, jCboFornecedor_bbd, jTxtTotal );
        compraProdutoControle.setList(new ArrayList());
        compraBbd = null;
 // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        Util.limparCampos(jTxtNumCompra, jFmtData, jCboFornecedor_bbd,  jTxtTotal);
        habilitar(true);
        compraProdutoControle.setList(new ArrayList());
        jTxtNumCompra.grabFocus();
        incluindo = true;
        compraBbd = new CompraBbd();
        // TODO add your handling code here:

    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnIncluirbbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirbbdActionPerformed
       JDlgCompraProduto jDlgCompraProduto = new JDlgCompraProduto(null, true);
        jDlgCompraProduto.setTitle("inclusão de produtos");
        jDlgCompraProduto.setTelaAnterior(this);
        jDlgCompraProduto.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnIncluirbbdActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
           if (Util.perguntar("Deseja excluir a compra ?") == true) {
            for (int i = 0; i < jTable1.getRowCount(); i++) {

                compraDao_bbd.delete(compraProdutoControle.getList(i));

            }
        } else {
            Util.mensagem("Compra não excluida");
        };     // TODO add your handling code here:

    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed

        if (compraBbd != null) {
            Util.habilitar(true, jFmtData, jTxtNumCompra, jTxtTotal, jCboFornecedor_bbd, 
                     jBtnConfirmar, jBtnCancelar, jBtnAlterarbbd, jBtnExcluirbbd, jBtnIncluirbbd);
            Util.habilitar(false, jBtnAlterar, jBtnExcluir, jBtnIncluir, jBtnPesquisar);
            incluindo = false;
        } else {
            Util.mensagem("Deve ser feita uma pesquisa antes");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
              compraBbd = viewBean();
        if (incluindo == true) {
            compraDao_bbd.insert(compraBbd);
            CompraProdutoDao_Bbd compraProdutoDAO = new CompraProdutoDao_Bbd();
            CompraProdutoBbd compraProduto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                compraProduto = compraProdutoControle.getBean(linha);
                compraProduto.setCompraBbd(compraBbd);
                compraProdutoDAO.insert(compraProduto);
            }
        } else {
            compraDao_bbd.update(compraBbd);
            //remover todos os pedidos produtos deste pedido

            //incluir todos os pedidosProduto que estao na tabela
            CompraProdutoDao_Bbd compraProdutoDAO = new CompraProdutoDao_Bbd();
            CompraProdutoBbd compraProdutos;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                compraProdutos = compraProdutoControle.getBean(linha);
                compraProdutos.setCompraBbd(compraBbd);
                compraProdutoDAO.insert(compraProdutos);
            }
        }
        habilitar(false);
        Util.limparCampos(jTxtNumCompra, jFmtData, jCboFornecedor_bbd, jTxtTotal);
        compraProdutoControle.setList(new ArrayList());

        compraBbd = null;  // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        JDlgCompraPesquisar jDlgCompraPesquisar = new JDlgCompraPesquisar(null, true);
        jDlgCompraPesquisar.setTelaAnterior(this);
        jDlgCompraPesquisar.setVisible(true);
        compraBbd = new CompraBbd();    
     
// TODO add your handling code here:
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnAlterarbbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarbbdActionPerformed
        int linSel = jTable1.getSelectedRow();
        if(linSel==-1){
            Util.mensagem("Nenhuma linha selecionada");
        }
        JDlgCompraProduto jDlgCompraProduto = new JDlgCompraProduto(null, true);
        jDlgCompraProduto.setTitle("Alterar Produto");
        jDlgCompraProduto.setTelaAnterior(this);
        CompraProdutoBbd compraProduto = (CompraProdutoBbd) compraProdutoControle.getBean(linSel);
        jDlgCompraProduto.beanView(compraProduto);
        jDlgCompraProduto.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAlterarbbdActionPerformed

    private void jBtnExcluirbbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirbbdActionPerformed
       int linha = jTable1.getSelectedRow();
        if (linha == -1) {
            Util.mensagem("Nenhuma linha selecionada");
        } else {
            if (Util.perguntar("Confirma exclusão do produto?") == true) {
                compraProdutoControle.removeBean(linha);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnExcluirbbdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCompra dialog = new JDlgCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterarbbd;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluirbbd;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluirbbd;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<FornecedorBbd> jCboFornecedor_bbd;
    private javax.swing.JTextField jFmtData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtNumCompra;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
