package bean;
// Generated 12/12/2023 15:11:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GrupoBbd generated by hbm2java
 */
@Entity
@Table(name="grupo_bbd"
    ,catalog="db_barbara_dias"
)
public class GrupoBbd  implements java.io.Serializable {


     private int idGrupoBbd;
     private String nomeBbd;
     private String tipoBbd;
     private String categoriaBbd;
     private Integer ativoBbd;

    public GrupoBbd() {
    }

	
    public GrupoBbd(int idGrupoBbd) {
        this.idGrupoBbd = idGrupoBbd;
    }
    public GrupoBbd(int idGrupoBbd, String nomeBbd, String tipoBbd, String categoriaBbd, int ativoBbd) {
       this.idGrupoBbd = idGrupoBbd;
       this.nomeBbd = nomeBbd;
       this.tipoBbd = tipoBbd;
       this.categoriaBbd = categoriaBbd;
       this.ativoBbd = ativoBbd;
    }
   
     @Id 

    
    @Column(name="idGrupo_bbd", unique=true, nullable=false)
    public int getIdGrupoBbd() {
        return this.idGrupoBbd;
    }
    
    public void setIdGrupoBbd(int idGrupoBbd) {
        this.idGrupoBbd = idGrupoBbd;
    }

    
    @Column(name="nome_bbd", length=225)
    public String getNomeBbd() {
        return this.nomeBbd;
    }
    
    public void setNomeBbd(String nomeBbd) {
        this.nomeBbd = nomeBbd;
    }

    
    @Column(name="tipo_bbd", length=225)
    public String getTipoBbd() {
        return this.tipoBbd;
    }
    
    public void setTipoBbd(String tipoBbd) {
        this.tipoBbd = tipoBbd;
    }

    
    @Column(name="categoria_bbd")
    public String getCategoriaBbd() {
        return this.categoriaBbd;
    }
    
    public void setCategoriaBbd(String categoriaBbd) {
        this.categoriaBbd = categoriaBbd;
    }

    
    @Column(name="ativo_bbd")
    public Integer getAtivoBbd() {
        return this.ativoBbd;
    }
    
    public void setAtivoBbd(Integer ativoBbd) {
        this.ativoBbd = ativoBbd;
    }

}


