package bean;
// Generated 12/12/2023 15:11:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuarioBbd generated by hbm2java
 */
@Entity
@Table(name="usuario_bbd"
    ,catalog="db_barbara_dias"
)
public class UsuarioBbd  implements java.io.Serializable {


     private int idusuarioBbd;
     private String nomeBbd;
     private String senhaBbd;
     private String nivelBbd;
     private Integer ativoBbd;
     private String apelidoBbd;
     private String cpfBbd;
     private Date dataNascBbd;

    public UsuarioBbd() {
    }

    public UsuarioBbd(int idusuarioBbd, String nomeBbd, String senhaBbd, String nivelBbd, Integer ativoBbd, String apelidoBbd, String cpfBbd, Date dataNascBbd) {
       this.idusuarioBbd = idusuarioBbd;
       this.nomeBbd = nomeBbd;
       this.senhaBbd = senhaBbd;
       this.nivelBbd = nivelBbd;
       this.ativoBbd = ativoBbd;
       this.apelidoBbd = apelidoBbd;
       this.cpfBbd = cpfBbd;
       this.dataNascBbd = dataNascBbd;
    }
   
     @Id 

    
    @Column(name="idusuario_bbd", unique=true, nullable=false)
    public int getIdusuarioBbd() {
        return this.idusuarioBbd;
    }
    
    public void setIdusuarioBbd(int idusuarioBbd) {
        this.idusuarioBbd = idusuarioBbd;
    }

    
    @Column(name="nome_bbd")
    public String getNomeBbd() {
        return this.nomeBbd;
    }
    
    public void setNomeBbd(String nomeBbd) {
        this.nomeBbd = nomeBbd;
    }

    
    @Column(name="senha_bbd")
    public String getSenhaBbd() {
        return this.senhaBbd;
    }
    
    public void setSenhaBbd(String senhaBbd) {
        this.senhaBbd = senhaBbd;
    }

    
    @Column(name="nivel_bbd", length=5)
    public String getNivelBbd() {
        return this.nivelBbd;
    }
    
    public void setNivelBbd(String nivelBbd) {
        this.nivelBbd = nivelBbd;
    }

    
    @Column(name="ativo_bbd")
    public Integer getAtivoBbd() {
        return this.ativoBbd;
    }
    
    public void setAtivoBbd(Integer ativoBbd) {
        this.ativoBbd = ativoBbd;
    }

    
    @Column(name="apelido_bbd")
    public String getApelidoBbd() {
        return this.apelidoBbd;
    }
    
    public void setApelidoBbd(String apelidoBbd) {
        this.apelidoBbd = apelidoBbd;
    }

    
    @Column(name="cpf_bbd", length=225)
    public String getCpfBbd() {
        return this.cpfBbd;
    }
    
    public void setCpfBbd(String cpfBbd) {
        this.cpfBbd = cpfBbd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNasc_bbd", length=10)
    public Date getDataNascBbd() {
        return this.dataNascBbd;
    }
    
    public void setDataNascBbd(Date dataNascBbd) {
        this.dataNascBbd = dataNascBbd;
    }

}


